//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.BLL.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ky {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ky() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBot.BLL.Helpers.Resources.Resources.ky", typeof(Resources_ky).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код ийгиликтүү текшерилди!.
        /// </summary>
        public static string CodeValidated {
            get {
                return ResourceManager.GetString("CodeValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сиз учурда киргенсиз.
        /// </summary>
        public static string CurrentlyInSystem {
            get {
                return ResourceManager.GetString("CurrentlyInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чечимин киргизиңиз:.
        /// </summary>
        public static string EnterSolution {
            get {
                return ResourceManager.GetString("EnterSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to жалпы маалымат.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Чечилди] [Код] [Деңгээл] [Пред. аймак] - [аты].
        /// </summary>
        public static string ListOfTasksDescription {
            get {
                return ResourceManager.GetString("ListOfTasksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лог тексти.
        /// </summary>
        public static string LogText {
            get {
                return ResourceManager.GetString("LogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суроо-талап туура түзүлдү.
        /// </summary>
        public static string QueryCorrect {
            get {
                return ResourceManager.GetString("QueryCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туура жоопту көрсөтүү.
        /// </summary>
        public static string ShowCorrectResultButton {
            get {
                return ResourceManager.GetString("ShowCorrectResultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кайра чечүү.
        /// </summary>
        public static string SolveAgainButton {
            get {
                return ResourceManager.GetString("SolveAgainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тапшырманы чечүү
        ///.
        /// </summary>
        public static string SolveProblemButton {
            get {
                return ResourceManager.GetString("SolveProblemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [чечилди] [код] - [тапшырманын аты].
        /// </summary>
        public static string SubmissionListDescription {
            get {
                return ResourceManager.GetString("SubmissionListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to таблицанын натыйжасы.
        /// </summary>
        public static string TableResultButton {
            get {
                return ResourceManager.GetString("TableResultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to маселелер.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тапшырманын сүрөттөлүшү.
        /// </summary>
        public static string TasksDescription {
            get {
                return ResourceManager.GetString("TasksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сураныч катталыңыз же https://solveway.club/ сайтына кириңиз
        ///профиль бөлүмүндө жашыруун код бар, аны бул жерге киргизиңиз:.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сенин чечимиң.
        /// </summary>
        public static string YourSolution {
            get {
                return ResourceManager.GetString("YourSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сиздин чечимдериңиз.
        /// </summary>
        public static string YourSubmissions {
            get {
                return ResourceManager.GetString("YourSubmissions", resourceCulture);
            }
        }
    }
}
