//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.BLL.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBot.BLL.Helpers.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code was successfully validated!.
        /// </summary>
        public static string CodeValidated {
            get {
                return ResourceManager.GetString("CodeValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in the system.
        /// </summary>
        public static string CurrentlyInSystem {
            get {
                return ResourceManager.GetString("CurrentlyInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter solution: .
        /// </summary>
        public static string EnterSolution {
            get {
                return ResourceManager.GetString("EnterSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general info.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed successfully.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [solved] [code] [level] [subject area]-[name].
        /// </summary>
        public static string ListOfTasksDescription {
            get {
                return ResourceManager.GetString("ListOfTasksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log text.
        /// </summary>
        public static string LogText {
            get {
                return ResourceManager.GetString("LogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is correct.
        /// </summary>
        public static string QueryCorrect {
            get {
                return ResourceManager.GetString("QueryCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correct result.
        /// </summary>
        public static string ShowCorrectResultButton {
            get {
                return ResourceManager.GetString("ShowCorrectResultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solve again.
        /// </summary>
        public static string SolveAgainButton {
            get {
                return ResourceManager.GetString("SolveAgainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solve task.
        /// </summary>
        public static string SolveProblemButton {
            get {
                return ResourceManager.GetString("SolveProblemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [solved] [code]-[task name].
        /// </summary>
        public static string SubmissionListDescription {
            get {
                return ResourceManager.GetString("SubmissionListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table result.
        /// </summary>
        public static string TableResultButton {
            get {
                return ResourceManager.GetString("TableResultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks description.
        /// </summary>
        public static string TasksDescription {
            get {
                return ResourceManager.GetString("TasksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please register/sign in at https://solveway.club/ 
        ///and enter secret code that is in you profile:.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your solution.
        /// </summary>
        public static string YourSolution {
            get {
                return ResourceManager.GetString("YourSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your submissions.
        /// </summary>
        public static string YourSubmissions {
            get {
                return ResourceManager.GetString("YourSubmissions", resourceCulture);
            }
        }
    }
}
